// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXRsWa2F-QpWtnKyDTBWa0J1KWyHTcuT4',
    appId: '1:110512021910:web:2786c6f7b933bbdbc23db7',
    messagingSenderId: '110512021910',
    projectId: 'burguer-a721e',
    authDomain: 'burguer-a721e.firebaseapp.com',
    storageBucket: 'burguer-a721e.appspot.com',
    measurementId: 'G-2ERKV9GLDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmvArXQ0gG93l5Z8L_824rDFJaIwT1gWo',
    appId: '1:110512021910:android:7901349a2002963cc23db7',
    messagingSenderId: '110512021910',
    projectId: 'burguer-a721e',
    storageBucket: 'burguer-a721e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPhYl9vdHgpsnvHarRyxhKi1IQlp2qxas',
    appId: '1:110512021910:ios:f30da6e59f14b3cec23db7',
    messagingSenderId: '110512021910',
    projectId: 'burguer-a721e',
    storageBucket: 'burguer-a721e.appspot.com',
    iosClientId: '110512021910-fsnk60hbrhka6i382aq8t0cbvt0ua4ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.burguer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPhYl9vdHgpsnvHarRyxhKi1IQlp2qxas',
    appId: '1:110512021910:ios:f30da6e59f14b3cec23db7',
    messagingSenderId: '110512021910',
    projectId: 'burguer-a721e',
    storageBucket: 'burguer-a721e.appspot.com',
    iosClientId: '110512021910-fsnk60hbrhka6i382aq8t0cbvt0ua4ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.burguer',
  );
}
